### This is the Terraform-generated prod-promote.yml workflow for the transmogrifier-prod app repository ###
name: Prod Promote Fargate Container
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    name: Prod Promote Fargate Container
    uses: mitlibraries/.github/.github/workflows/fargate-shared-promote-prod.yml@main
    secrets: inherit
    with:
      AWS_REGION: "us-east-1"
      GHA_ROLE_STAGE: transmogrifier-gha-stage
      GHA_ROLE_PROD: transmogrifier-gha-prod
      ECR_STAGE: "transmogrifier-stage"
      ECR_PROD: "transmogrifier-prod"
